### ISSUE TITLE
Remote process communication

### ISSUE THREAD

**Issue by trustmaster** [trustmaster/goflow#12]
Once we have a framework to turn a visual graph into a running app, the next step is  to let different flow-based apps talk to each other by means of remote ports and connections.

It would be nice to make such communication compatible with NoFlo network protocol noflo/noflo#107, so NoFlo graphs could talk to GoFlow and vice versa.

**Comment by mackristof** [comment]
Perhaps with GRpc =>https://github.com/grpc/grpc-common/tree/master/go
