### ISSUE TITLE
NoFlo runtime implementation

### ISSUE THREAD

**Issue by trustmaster** [trustmaster/goflow#19]
Implement a runtime for [Flowhub](http://flowhub.io) / [NoFlo-UI](https://github.com/noflo/noflo-ui/) using the [FBP Network Protocol](http://noflojs.org/documentation/protocol/) and WebSockets.

**Comment by pierrebeaucamp** [comment]
I'm very interested in using Go + Flowhub so I would love to see an implementation of this. Could you point out the exact status of this issue and what still needs to be done?

Thank you

**Comment by trustmaster** [comment]
@pierrebeaucamp Currently implemented:

 - Runtime discovery
 - Graph protocol (complete)
 - Component protocol (listing)

Todo:

 - More tests for component protocol
 - Network protocol
 - Runtime protocol (talking to main graph)
