### ISSUE TITLE
IIP in Component InPort results in uninitialized Channel and deadlocks.

### ISSUE THREAD

**Issue by luiscarrasco** [trustmaster/goflow#22]
If I have a Component with a port and add an Initial Information Package to it without making the port an Inport for the network, the underlying channel does not get initialized. 

In component.go the check for the channel not being nil will be true and therefore the recv handler does not get initialized. This results in a deadlock of threads.

I hope this is descriptive enough.

**Comment by trustmaster** [comment]
Should have been fixed in current `master`.
