### ISSUE TITLE
Multiple Inputs connecting to same Output

### ISSUE THREAD

**Issue by Chillance** [trustmaster/goflow#36]
Hey!

I recall reading somewhere that this doesn't support multiple connections to the same connector, but is this something that could be made possible?

I'm making a node system that will enable connecting several different inputs to the same output, so this is why I'm wondering.

Thanks!

**Comment by lovromazgon** [comment]
According to @trustmaster this [has been implemented](https://github.com/trustmaster/goflow/issues/3#issuecomment-26655148) and is called "Array Ports". I would also like to use this feature but can't find any examples. Could someone help me out please?

**Comment by trustmaster** [comment]
The test you are looking for is here: https://github.com/trustmaster/goflow/blob/master/network_test.go#L193 (see the component using it above, it's called `rr`).
