### ISSUE TITLE
Some code makes me confused

### ISSUE THREAD

**Issue by HouLinwei** [trustmaster/goflow#47]
Thank you for your code. But when I read it,  the code
https://github.com/trustmaster/goflow/blob/master/network.go#L187
https://github.com/trustmaster/goflow/blob/master/network.go#L188
makes  confused. 
At line 180 or 194 in the same function, the variable ’vNet‘ has been assigned. and why assign ’vNet‘ the value of 'n'? 
What's more,  'vNet' is a left value and never be used again. So why we need 'vNet'?
It really makes me confused.

I will appreciate it if you help me.

Thank you anyway.

**Comment by trustmaster** [comment]
Closing as this thread is too old and irrelevant for current `master`
